apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: student-operator
  template:
    metadata:
      labels:
        name: student-operator
    spec:
      serviceAccountName: student-operator
      containers:
        - name: student-operator
          # Replace this with the built image name
          image: docker.io/dcota1/student-operator:v1
          command:
          - student-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "student-operator"
