// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StudentAPI) DeepCopyInto(out *StudentAPI) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Stat.DeepCopyInto(&out.Stat)
	in.Info.DeepCopyInto(&out.Info)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StudentAPI.
func (in *StudentAPI) DeepCopy() *StudentAPI {
	if in == nil {
		return nil
	}
	out := new(StudentAPI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StudentAPI) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StudentAPIInfo) DeepCopyInto(out *StudentAPIInfo) {
	*out = *in
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StudentAPIInfo.
func (in *StudentAPIInfo) DeepCopy() *StudentAPIInfo {
	if in == nil {
		return nil
	}
	out := new(StudentAPIInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StudentAPIList) DeepCopyInto(out *StudentAPIList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StudentAPI, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StudentAPIList.
func (in *StudentAPIList) DeepCopy() *StudentAPIList {
	if in == nil {
		return nil
	}
	out := new(StudentAPIList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StudentAPIList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StudentAPISpec) DeepCopyInto(out *StudentAPISpec) {
	*out = *in
	if in.Servers != nil {
		in, out := &in.Servers, &out.Servers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StudentAPISpec.
func (in *StudentAPISpec) DeepCopy() *StudentAPISpec {
	if in == nil {
		return nil
	}
	out := new(StudentAPISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StudentAPIStat) DeepCopyInto(out *StudentAPIStat) {
	*out = *in
	if in.Servers != nil {
		in, out := &in.Servers, &out.Servers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StudentAPIStat.
func (in *StudentAPIStat) DeepCopy() *StudentAPIStat {
	if in == nil {
		return nil
	}
	out := new(StudentAPIStat)
	in.DeepCopyInto(out)
	return out
}
