apiVersion: "netgroup.com/v1"
kind: StudentAPI
metadata:
  name: davidec
spec:
  ID: "s263084"
  name: "Davide"
  surname: "Cota"
  startThesis: "01/11/2019"
  SSHPub: "any key"
  role:
    thesis: "student-as-a-service"
    PhD: "Cloud"
    post-doc: "any"
