---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  name: my-server
  namespace: dcota-ns1
spec:
  terminationGracePeriodSeconds: 30
  domain:
    cpu:
      cores: 1
    resources:
      requests:
        cpu: 1
        memory: 1024Mi
      limits:
        cpu: 1
        memory: 2048Mi
    devices:
      disks:
      - name: containerdisk
        disk:
          bus: virtio
      - name: cloudinitdisk
        disk:
          bus: virtio
  volumes:
  - name: containerdisk
    containerDisk:
      image: andreacossio/ubuntu_server:latest
  - name: cloudinitdisk
    cloudInitNoCloud:
      secretRef:
        name: adm-key
