apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tenants.netgroup.com
spec:
  group: netgroup.com
  names:
    kind: Tenant
    listKind: TenantList
    plural: tenants
    singular: tenant
  scope: Namespaced
  validation:
    openAPIV3Schema:
      description: Tenant is the Schema for the tenants API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        info:
          properties:
            email:
              description: tenant email
              minLength: 1
              type: string
            group:
              description: tenant group
              minLength: 1
              type: string
            id:
              description: tenant id
              minLength: 1
              type: string
            name:
              description: tenant name
              minLength: 1
              type: string
            publicKey:
              description: tenant PublickKey
              minLength: 1
              type: string
            roles:
              description: user roles
              items:
                type: string
              type: array
            surname:
              description: tenant surname
              minLength: 1
              type: string
          required:
          - email
          - id
          - name
          - publicKey
          - roles
          - surname
          type: object
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: TenantSpec defines the desired state of Tenant
          properties:
            hosts:
              items:
                type: string
              type: array
          type: object
        stat:
          description: TenantStatus defines the observed state of Tenant
          properties:
            hosts:
              items:
                type: string
              type: array
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
