apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: studentapis.netgroup.com
spec:
  group: netgroup.com
  names:
    kind: StudentAPI
    listKind: StudentAPIList
    plural: studentapis
    singular: studentapi
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: StudentAPI is the Schema for the studentapis API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        info:
          description: StudentAPIInfo defines the general info of the user
          properties:
            id:
              description: student id
              minLength: 1
              type: string
            name:
              description: student name
              minLength: 1
              type: string
            publicKey:
              description: student PublickKey
              minLength: 1
              type: string
            roles:
              description: user roles
              items:
                type: string
              type: array
            surname:
              description: student surname
              minLength: 1
              type: string
          required:
          - id
          - name
          - publicKey
          - roles
          - surname
          type: object
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: StudentAPISpec defines the desired state of the object
          properties:
            servers:
              items:
                type: string
              type: array
          type: object
        stat:
          description: StudentAPIStat defines the observed state of the object
          properties:
            servers:
              items:
                type: string
              type: array
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
